### ISSUE TITLE
Selecting the Frontend tech

### ISSUE THREAD

**Issue by WiegnerO** [WiegnerO/GuessingGame#3]
Here we will decide the front end tech
Prob keep it 
React
Vite
switch from canvaskit to tailwind

**Comment by torbensky** [comment]
Maybe we should use NextUI? https://nextui.org/docs/frameworks/vite

It's a React library built on top of Tailwind. Seems pretty slick!

**Comment by torbensky** [comment]
Also https://preline.co/ looks nice

**Comment by torbensky** [comment]
Other frameworks to consider:

- https://mantine.dev/ (new, looks neat, idk much about it)
- https://react-bootstrap.github.io/ (good ol' Bootstrap!)
- MUI (good, but boring)
- https://primereact.org/ (popular, but kinda uninspiring looking)
- https://v2.grommet.io/ (it has a browser designer app which is quite cool)
- https://ant.design/ (probably the biggest competitor to MUI, it's a competing design system)
- https://react.semantic-ui.com/ (library focused on creating clean, semantic HTML, which I really like)

**Comment by torbensky** [comment]
https://www.chakra-ui.com/

**Comment by WiegnerO** [comment]
hmm for now im between tailwind and NextUI
